### ISSUE TITLE
Problem of getting humidity

### ISSUE THREAD

**Issue by ICEpower1** [heinemml/co2meter#4]
Hello,

Thanks for the great code! It has worked fine and I would like to continue using it. But I noticed that the program does not give me the value of humidity. I have used the program for ZyAura ZG1683R (U) Desktop CO2 monitor. 

With Henryk Plötz's original code I was able to print humidity from my device, so I think it should be possible with your code as well. I tried to solve the problem myself by examining the CO2Meter.py file, but I couldn't find a problem yet. I wonder if you had a clue where the problem might be?

Thanks!

**Comment by heinemml** [comment]
Hi,

happy to hear that this code is useful to you. 
I'm not really sure why you might not see the humidity if your device supports it. Mine doesn't so I can't test it.

Can you add a print of `operation` after this line? https://github.com/heinemml/CO2Meter/blob/57d0bb5d3b280dbf53c12e1becadcb9eaf8e8791/CO2Meter.py#L61

This should show if you actually get readings with key `0x44`. 

Is the Code of Henryk showing you the Value as actual Humidity or do you see it with another key?

**Comment by ICEpower1** [comment]
Got it working. Now that I got the idea from you to check the readings, I changed the number from CO2Meter.py and now the program also prints the humidity! 

So what I did was change the number 0x44 to 0x41 from line 8. I noticed that Henryk Plötz's original script used also the number 0x44, so now I'm not sure where the test script I used earlier came from (lol). But it gave me the idea to change that number to 0x41.

Thanks for the assist, everything is working fine now! :)

**Comment by heinemml** [comment]
I just had a look at the [AppNote](http://co2meters.com/Documentation/AppNotes/AN146-RAD-0401-serial-communication.pdf) he is referring to in the article.

They describe Humidity as follows:
```
The Hex format of Item code, 41-> the hex format of letter “A” RH Item Code. 
```

So 41 seems to be correct and I have no Idea where Henryk got the 44 from. And also what Code you found where ;)

I'll fix this in the repo.
