### ISSUE TITLE
Checksum error

### ISSUE THREAD

**Issue by spranta1977** [heinemml/co2meter#5]
First of all, your Module is great. 
We bought a AirCo2nTrol Mini last week, Kazt.Nr. 31.5006.02 Build 08/20 and the module isn't working anymore.
71 04 00 75 0D 00 00 00 => F4 52 20 5C 41 F1 E8 46 Checksum error
50 04 65 B9 0D 00 00 00 => 70 F2 1C 3C 41 F1 E8 2F Checksum error
57 1E 3F B4 0D 00 00 00 => DB 32 1C 1C 44 31 E8 2E Checksum error
56 2C 37 B9 0D 00 00 00 => 7A 32 1C FC 46 F1 E8 2F Checksum error
41 00 00 41 0D 00 00 00 => 74 52 1A 5C 41 71 E8 44 Checksum error
43 0D E5 35 0D 00 00 00 => E0 F2 1A 9C 42 11 E8 3E Checksum error
42 12 9E F2 0D 00 00 00 => 07 12 1A 7C 43 B1 E8 36 Checksum error
6D 0D F7 71 0D 00 00 00 => 62 32 1F DC 42 11 E8 46 Checksum error
6E 30 26 C4 0D 00 00 00 => D8 12 1F FC 47 71 E8 34 Checksum error
71 03 FE 72 0D 00 00 00 => 03 12 20 5C 41 D1 E8 46 Checksum error
50 04 63 B7 0D 00 00 00 => B0 B2 1C 3C 41 F1 E8 2E Checksum error
4F 21 8A FA 0D 00 00 00 => 05 92 1B 1C 45 91 E8 37 Checksum error
52 2C 11 8F 0D 00 00 00 => B6 72 1C 7C 46 F1 E8 2D Checksum error
41 00 00 41 0D 00 00 00 => 74 52 1A 5C 41 71 E8 44 Checksum error
43 0D E7 37 0D 00 00 00 => A0 32 1A 9C 42 11 E8 3E Checksum error
42 12 9E F2 0D 00 00 00 => 07 12 1A 7C 43 B1 E8 36 Checksum error

Any ideas?
Thanks
Alex

**Comment by heinemml** [comment]
That's an interesting symptom. Seems like they removed the "encryption" on the Data.

This is the output from my device:
```
E4 E4 66 20 88 46 BF 22  =>  50 02 6E C0 0D 00 00 00
72 E4 5F 20 CD 46 BF 6A  =>  4F 1A 20 89 0D 00 00 00
32 E4 77 20 9C 46 BF 32  =>  52 24 08 7E 0D 00 00 00
70 E4 EE 20 FC 46 BF 2A  =>  41 00 00 41 0D 00 00 00
E0 E4 FE 20 64 46 BF 32  =>  43 0D EE 3E 0D 00 00 00
36 E4 F6 20 09 46 BF 02  =>  42 12 A8 FC 0D 00 00 00
A2 E4 4E 21 64 46 BF A2  =>  6D 0D F6 70 0D 00 00 00
F7 E4 57 21 60 46 BF 9A  =>  6E 2D 70 0B 0D 00 00 00
34 E4 6E 21 8A 46 BF 1A  =>  71 02 48 BB 0D 00 00 00
E4 E4 66 20 88 46 BF 22  =>  50 02 6E C0 0D 00 00 00
4A E4 1E 20 2D 46 BF 62  =>  57 16 1B 88 0D 00 00 00
E2 E4 17 20 9D 46 BF 62  =>  56 24 0E 88 0D 00 00 00
70 E4 EE 20 FC 46 BF 2A  =>  41 00 00 41 0D 00 00 00
D8 E4 FE 20 64 46 BF 0A  =>  43 0D ED 3D 0D 00 00 00
36 E4 F6 20 09 46 BF 02  =>  42 12 A8 FC 0D 00 00 00
A2 E4 4E 21 64 46 BF A2  =>  6D 0D F6 70 0D 00 00 00
F7 E4 57 21 60 46 BF 9A  =>  6E 2D 70 0B 0D 00 00 00
34 E4 6E 21 8A 46 BF 1A  =>  71 02 48 BB 0D 00 00 00
```

[This code](https://github.com/heinemml/CO2Meter/blob/master/CO2Meter.py#L69) checks if `decrypted[4] != 0x0d` to determine if the decryption worked. But your input already has the `0x0d` at the 4th byte. So the decryption in fact scrambles the data.

Could you try replace in line 68 
```python
decrypted = self._decrypt(data)
```
with

```python
decrypted = data
```

**Comment by spranta1977** [comment]
Hi, thanks for the quick answer.
I replaced decrypted = data
Sorry, I’m just starting to learn python.
I’ve I ran the following code I’m getting no error and no result – have can I print out the result?
from CO2Meter import *
import time
sensor = CO2Meter("/dev/hidraw0")
while True:
    time.sleep(2)
    sensor.get_data()
Thanks ☺

from CO2Meter import *
import time
sensor = CO2Meter("/dev/hidraw0")
while True:
    time.sleep(2)
    sensor.get_data()
    print(CO2METER_TEMP)

output = 66


Von: Michael Nosthoff <notifications@github.com>
Gesendet: Mittwoch, 9. September 2020 17:21
An: heinemml/CO2Meter <CO2Meter@noreply.github.com>
Cc: Sötz Alexander <Alexander.soetz@egger.com>; Author <author@noreply.github.com>
Betreff: Re: [heinemml/CO2Meter] Checksum error (#5)

⚠ EXTERNAL SENDER



That's an interesting symptom. Seems like they removed the "encryption" on the Data.

This is the output from my device:

E4 E4 66 20 88 46 BF 22  =>  50 02 6E C0 0D 00 00 00

72 E4 5F 20 CD 46 BF 6A  =>  4F 1A 20 89 0D 00 00 00

32 E4 77 20 9C 46 BF 32  =>  52 24 08 7E 0D 00 00 00

70 E4 EE 20 FC 46 BF 2A  =>  41 00 00 41 0D 00 00 00

E0 E4 FE 20 64 46 BF 32  =>  43 0D EE 3E 0D 00 00 00

36 E4 F6 20 09 46 BF 02  =>  42 12 A8 FC 0D 00 00 00

A2 E4 4E 21 64 46 BF A2  =>  6D 0D F6 70 0D 00 00 00

F7 E4 57 21 60 46 BF 9A  =>  6E 2D 70 0B 0D 00 00 00

34 E4 6E 21 8A 46 BF 1A  =>  71 02 48 BB 0D 00 00 00

E4 E4 66 20 88 46 BF 22  =>  50 02 6E C0 0D 00 00 00

4A E4 1E 20 2D 46 BF 62  =>  57 16 1B 88 0D 00 00 00

E2 E4 17 20 9D 46 BF 62  =>  56 24 0E 88 0D 00 00 00

70 E4 EE 20 FC 46 BF 2A  =>  41 00 00 41 0D 00 00 00

D8 E4 FE 20 64 46 BF 0A  =>  43 0D ED 3D 0D 00 00 00

36 E4 F6 20 09 46 BF 02  =>  42 12 A8 FC 0D 00 00 00

A2 E4 4E 21 64 46 BF A2  =>  6D 0D F6 70 0D 00 00 00

F7 E4 57 21 60 46 BF 9A  =>  6E 2D 70 0B 0D 00 00 00

34 E4 6E 21 8A 46 BF 1A  =>  71 02 48 BB 0D 00 00 00

This code<https://protection.retarus.com/v1?u=https%3A%2F%2Fgithub.com%2Fheinemml%2FCO2Meter%2Fblob%2Fmaster%2FCO2Meter.py%23L69&c=3ii9GcD&r=oAvtbLc8RAgyO0hNz50Do&k=7s1&s=ZF1OiZRsD2TC9HM7NHFZdtfwqGyj9RWeodkzoNA3u5o> checks if decrypted[4] != 0x0d to determine if the decryption worked. But your input already has the 0x0d at the 4th byte. So the decryption in fact scrambles the data.

Could you try replace in line 68

decrypted = self._decrypt(data)

with

decrypted = data

**Comment by spranta1977** [comment]
Managed it by myselfe - yes you are write, the encryption is deactivated :)

**Comment by heinemml** [comment]
Thanks for the confirmation. I updated the code to check if the data is already decrypted.

If you installed using pip you should be able to get the last version by running 
``` 
pip install git+https://github.com/heinemml/CO2Meter
``` 
again.

Thanks for Reporting!
